apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-pvc
  namespace: code-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn # ganti sesuai StorageClass Longhorn kamu
  resources:
    requests:
      storage: 5Gi
